### PR TITLE
Update to 0.16

### PR DESCRIPTION
**Pull request by Warry**

### CODE REVIEW

**Comment by evancz** [comment]
Do you use this? I kind of want to not update this until someone asks because I think it's a bad idea.

**Comment by Warry** [comment]
Actually I'm not using it anymore. It was good learning material though!

**Comment by evancz** [comment]
I guess it's not a huge deal to publish it. Maybe I'll just make the messaging about "I think this is a bad idea" more prominent :)

Thanks for the updates!

**Comment by vito** [comment]
Having read the warning I agree with it generally. And then immediately ran into a place in my own project where it would be very useful. :) I'd like to see a new version published for 0.16.0, though looking at the implementation it's very tiny so vendoring or rolling our own would be pretty painless.

If you're interested in the use case: my project is a CI system that provides the user with a way to describe an arbitrarily nested "execution plan", which is a declarative data structure basically describing "do this, do that, fetch these 3 things in parallel, and run this script". The UI reflects a one-to-one mapping to this structure, with a single recursive data type as the backing model.

Events are coming in as the plan executes (with, say, console output or saying that step X failed), and result in actions fed into `update`. Each event is annotated with an ID denoting which step it came from. My plan was to have a mapping from that ID to a Focus, which would make it very easy to update the model for the step related to the event, while preserving the tree structure to make it easy to implement `view` with recursion.

I guess what makes it seem like it doesn't fit the "anti-pattern" is that it's really only being used for one recursive type, where all the data is user-provided, and not really crossing abstraction boundaries.

**Pull request merged**
